Write-Host "SHL Assessment Recommender — Final CSV Generation Checklist"
Write-Host "=================================================="
Write-Host "This is a checklist; these commands will NOT be executed automatically. Run them manually if you need to fix environment issues."
Write-Host ""
Write-Host "1) Uninstall potentially incompatible packages:"
Write-Host "   pip uninstall -y tokenizers huggingface-hub sentence-transformers transformers"
Write-Host ""
Write-Host "2) Reinstall compatible versions:"
Write-Host "   pip install sentence-transformers==2.6.1 transformers==4.38.2 tokenizers==0.15.2 huggingface-hub==0.20.3"
Write-Host ""
Write-Host "3) Reinstall project requirements:"
Write-Host "   pip install -r requirements.txt"
Write-Host ""
Write-Host "4) Generate the predictions CSV (final artifact):"
Write-Host "   python generate_predictions.py"
Write-Host ""
Write-Host "Notes:"
Write-Host "- Only perform the steps above if you experienced import errors related to sentence-transformers / tokenizers."
Write-Host "- The generated file 'test_predictions.csv' is the final submission file."
